### ISSUE TITLE
Source changed, invalidating URLTextSearcher query

### ISSUE THREAD

**Issue by swy** [autopkg/thenikola-recipes#15]
Screaming Frog has again changed the page format, so the URLTextSearcher query can't find anything:

autopkg run -vv ScreamingFrogSEO.download.recipe
Processing ScreamingFrogSEO.download.recipe...
URLTextSearcher
{'Input': {'re_pattern': u'(?P<url>https://www.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-(?P<version>.*?).dmg)',
           'url': u'https://www.screamingfrog.co.uk/seo-spider/check-updates/'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
No match found on URL: https://www.screamingfrog.co.uk/seo-spider/check-updates/
Failed.
Receipt written to /Users/syuroff/Library/AutoPkg/Cache/com.github.thenikola.download.ScreamingFrogSEO/receipts/ScreamingFrogSEO.download-receipt-20160908-120232.plist

The following recipes failed:
    ScreamingFrogSEO.download.recipe
        Error in com.github.thenikola.download.ScreamingFrogSEO: Processor: URLTextSearcher: Error: No match found on URL: https://www.screamingfrog.co.uk/seo-spider/check-updates/

Nothing downloaded, packaged or imported.

**Comment by thenikola** [comment]
fixed again... Wish that site would quit changing.  I've reached out to them to get them to add the necessary pieces to do code verification though.  Thanks again for the report.

**Comment by swy** [comment]
Looks good- can you tell me where you were looking to determine the new SEARCH_URL to apply SEARCH_PATTERN to?  I don't see it in the previously used source.

**Comment by thenikola** [comment]
Honestly I just searched through the source code on their webpage, they have javascript that calls the new search URL when you click download.

**Comment by swy** [comment]
I hoped to give you a fixed PR, but didn't find the URL.  Now that I know what I'm looking for, I can see the URL in Chrome: Developer: Network.
Anyway, thanks for the update, and let's hope they get persuaded to stop moving it around and breaking the recipe.
