### ISSUE TITLE
CodeKit download recipe - SPARKLE_FEED_URL

### ISSUE THREAD

**Issue by blackthroat** [autopkg/thenikola-recipes#20]
`SPARKLE_FEED_URL` no longer being maintained, last update was for `3.0.6` which was released 2/22/17. Current version is `3.3` and can be downloaded from https://codekitapp.com/binaries/codekit.zip

**Comment by thenikola** [comment]
Thanks for the report, sorry I didn't catch it myself, I don't use CodeKit anymore.

I've updated the SparkleFeed URL to https://codekitapp.com/api/3/appcast.xml
