### ISSUE TITLE
NAME variable issue

### ISSUE THREAD

**Issue by cwatts-nomensa** [autopkg/thenikola-recipes#22]
The value of the %NAME% variable is resulting in "Axure RP %MAJOR_VERSION%" when using 'autopkg make-override AxureRP.munki.recipe'.

That is to say that the %MAJOR_VERSION% isn't substituted for the value, e.g. 8.

**Comment by thenikola** [comment]
I took a look at this and it seems to be working correctly on my end.  When I create the override I'm able to sub in whatever I'd like for the %MAJOR_VERSION% variable and it seems to work.  That being said I am only able to test this locally, I do not have access to a production munki environment.  

Can you describe what the override is doing, vs what you expect it to be doing?  I may have just misunderstood what you are attempting.
