### ISSUE TITLE
autopkg run -v GoToMeeting.munki fails with SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by peterkelm** [autopkg/thenikola-recipes#23]
$$ autopkg run -v GoToMeeting.munki
Processing GoToMeeting.munki...
GoToMeetingURLProvider
Can't read https://builds.cdn.getgo.com/g2mupdater/live/config.json: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
Failed.
Receipt written to ~/Library/AutoPkg/Cache/local.munki.GoToMeeting/receipts/GoToMeeting-receipt-20180318-113712.plist

The following recipes failed:
    GoToMeeting.munki
        Error in local.munki.GoToMeeting: Processor: GoToMeetingURLProvider: Error: Can't read https://builds.cdn.getgo.com/g2mupdater/live/config.json: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>

Nothing downloaded, packaged or imported.
$$

**Comment by thenikola** [comment]
This appears to be working for me, can you test again?  I tested on autopkg 1.0.3 and 1.0.4

**Comment by peterkelm** [comment]
Thanks for looking into this. I can confirm that the issue is still present on my machine.

I am running 10.12.6 currently (fully patched), using the Apple supplied Python 2.7.10 without modifications/additions.

Downloading that "config.json" file via curl works fine (reporting a TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256)

I extracted this line from your autopkg script and ran it interactively:
`urllib2.urlopen("https://builds.cdn.getgo.com/g2mupdater/live/config.json").read()`

...and it fails with the same error message as per my initial report. The GoToMeeting server seems to absolutely require the TLS SNI extension as running the same line with other (non-SNI) URLs/webservers works absolutely fine.

Below stackoverflow thread identifies this as a problem with Python 2.x (!) and the TLS SNI extension:
https://stackoverflow.com/questions/30918761/sslv3-alert-handshake-failure-with-urllib2#30925034

Unfortunately I haven't found a fix (yet) that I could propose.

**Comment by thenikola** [comment]
Unfortunately I don't think I'm going to be able to fix this.  I no longer manage a mac environment so I only have access to my personal Macbook to do any kind of testing.  I'm leaving the issue open but I doubt I'll be able to come up with a fix.  You may also want to keep an eye out over at https://github.com/autopkg/homebysix-recipes/issues/149 they forked this recipe a few years back instead of sending a pull request.  It's a much more popular repo so it will likely get fixed over there first.

**Comment by peterkelm** [comment]
Thanks for the pointer to https://github.com/autopkg/homebysix-recipes/issues/149. That's indeed describing exactly the same issue.
