### ISSUE TITLE
Screaming Frog SEO downloading Silicon version

### ISSUE THREAD

**Issue by opus-nbonenberger** [autopkg/thenikola-recipes#37]
Hi. The recipe downloads the new Silicon version of Screaming Frog SEO Spider. Can you adjust the recipe to download the Intel version?

There are 3 options on how you could adjust the recipe

- Let the recipe build a pkg with both versions and install the one depending on the architecture
- Create two separate recipes, one for each platform
- Use a configuration key of sorts to let recipe user decide which version he/she wants

**Comment by thenikola** [comment]
Thank you for the report, due I'll be able to take a look in this in a week or 2.

**Comment by paul-cossey** [comment]
I've just raised a PR that should address this: https://github.com/autopkg/thenikola-recipes/pull/39
