### ISSUE TITLE
Amethyst download recipe is broken

### ISSUE THREAD

**Issue by ahaupt11** [autopkg/thenikola-recipes#6]
local.munki.Amethyst: Processor: SparkleUpdateInfoProvider: Error: Can't open URL https://ianyh.com/amethyst/appcast.xml

Thanks in advance!

**Comment by thenikola** [comment]
Thanks for the report, I probably won't be able to take a look at this until Saturday.

**Comment by thenikola** [comment]
This is being addressed in AutoPkg 0.5.3 (no release date yet to my knowledge).  I've confirmed that it is now working against Git Master.

**Comment by thenikola** [comment]
Confirmed that this is working with the newly released Autopkg 0.6.1
