### ISSUE TITLE
Screaming Frog SEO fails to run

### ISSUE THREAD

**Issue by swy** [autopkg/thenikola-recipes#8]
autopkg run -v ScreamingFrogSEO.download.recipe
Processing ScreamingFrogSEO.download.recipe...
ScreamingFrogSeoURLProvider
global name 'base_url' is not defined
Failed.
Receipt written to /Users/syuroff/Library/AutoPkg/Cache/com.github.thenikola.download.ScreamingFrogSEO/receipts/ScreamingFrogSEO.download-receipt-20160428-172235.plist

The following recipes failed:
    ScreamingFrogSEO.download.recipe
        Error in com.github.thenikola.download.ScreamingFrogSEO: Processor: ScreamingFrogSeoURLProvider: Error: global name 'base_url' is not defined

Nothing downloaded, packaged or imported.

**Comment by thenikola** [comment]
Thanks for the report, it will probably be about a week before I can take a look at it, really busy with work.

**Comment by thenikola** [comment]
Rewrote the recipe using URLTextSearch processor and deleted the custom processor that previously discovered the download link.  This should be more resilient to future changes.  Thanks for the report.

**Comment by swy** [comment]
You're welcome, and thank you for attending to it.  But I believe you haven't yet pushed your changes to github for the rest of us: last commits for ScreamingFrog are currently  10/24/14

**Comment by thenikola** [comment]
Sorry about that, I'm not used to the new GitHub app.  Should be synced now.

**Comment by swy** [comment]
Confirmed On behalf of other Screaming Frog users, thanks for the tweak.
